import {
  Button,
  DropdownMenu,
  DropdownItem,
  Dropdown,
  Breadcrumb,
  BreadcrumbItem,
  Badge,
  Dialog,
  Table,
  Tag,
  TableColumn,
  Upload,
  Menu,
  MenuItem,
  Submenu,
  Row,
  Col,
  Card,
  Progress,
  Tabs,
  TabPane,
  Form,
  FormItem,
  Carousel,
  Timeline,
  TimelineItem,
  CarouselItem,
  Popconfirm,
  Input,
  Tree,
  RadioGroup,
  RadioButton
} from "element-ui";
import Vue from "vue";

Vue.use(Button);
Vue.use(DropdownMenu);
Vue.use(DropdownItem);
Vue.use(Dropdown);
Vue.use(Breadcrumb);
Vue.use(BreadcrumbItem);
Vue.use(Badge);
Vue.use(Dialog);
Vue.use(Table);
Vue.use(Tag);
Vue.use(TableColumn);
Vue.use(Upload);
Vue.use(Menu);
Vue.use(MenuItem);
Vue.use(Submenu);
Vue.use(Row);
Vue.use(Col);
Vue.use(Card);
Vue.use(Progress);
Vue.use(Tabs);
Vue.use(TabPane);
Vue.use(Form);
Vue.use(FormItem);
Vue.use(Carousel);
Vue.use(Timeline);
Vue.use(TimelineItem);
Vue.use(CarouselItem);
Vue.use(Popconfirm);
Vue.use(Input);
Vue.use(Tree);
Vue.use(RadioGroup);
Vue.use(RadioButton);
